spring:
  name: springbootexample
server:
  port: 8055
  servlet:
    context-path: /springbootexample
---
spring:
  profiles: scheduling
scheduling:
  period-in-seconds: 5
  range: 1000
---
spring:
  profiles: mongo-aggregation
  data:
    mongodb:
      host: 192.168.56.100
      port: 27017
      database: home
---
spring:
  profiles: dynamic-bean-creation
clients:
  all: alfa, beta
  alfa:
    url: http://127.0.0.1:8081/
  beta:
    url: http://127.0.0.1:8082/